# Data Preprocessing - Some Common Methods

In [1]:
import numpy as np
import pandas as pd

In [2]:
#reading the dataset
df=pd.read_csv("emp.csv")
df.head()

  id      name  salary  start_date        dept
0  1      Rick  623.30  01-01-2012          IT
1  2       Dan  515.20  23-09-2013  Operations
2  3  Michelle     NaN  15-11-2014          IT
3  4      Ryan  729.00  11-05-2014          HR
4         Gary  843.25  27-03-2015     Finance

In [3]:
#To check for missing values in column
df['name'].isnull()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
Name: name, dtype: bool

In [4]:
df['salary'].isnull()

0    False
1    False
2     True
3    False
4    False
5    False
6    False
7    False
Name: salary, dtype: bool

In [5]:
df['id'].isnull()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
Name: id, dtype: bool

In [6]:
df['salary'].sum()

13144.05

In [7]:
df['salary'].mean()

1877.7214285714285

In [8]:
#filling missing values
df['salary'].fillna(0)

0     623.30
1     515.20
2       0.00
3     729.00
4     843.25
5    8478.00
6    1032.80
7     922.50
Name: salary, dtype: float64

In [9]:
df=pd.read_csv('emp.csv')

In [10]:
#filling with nearby values
df['salary'].fillna(method='ffill')

0     623.30
1     515.20
2     515.20
3     729.00
4     843.25
5    8478.00
6    1032.80
7     922.50
Name: salary, dtype: float64

In [11]:
#dropping of na values
df['salary'].dropna()

0     623.30
1     515.20
3     729.00
4     843.25
5    8478.00
6    1032.80
7     922.50
Name: salary, dtype: float64

In [ ]:
df.head()

In [12]:
df=pd.read_csv('emp.csv')

In [17]:
df.head()

    id      name  salary  start_date        dept
0  1.0      Rick  623.30  01-01-2012          IT
1  2.0       Dan  515.20  23-09-2013  Operations
2  3.0  Michelle     NaN  15-11-2014          IT
3  4.0      Ryan  729.00  11-05-2014          HR
4  NaN      Gary  843.25  27-03-2015     Finance

In [ ]:
df.dropna()

In [16]:
df['id'].isnull()

0    False
1    False
2    False
3    False
4     True
5    False
6    False
7    False
Name: id, dtype: bool

In [19]:
#replace a value
df['name'].replace({"Rick":"Mike"})

0        Mike
1         Dan
2    Michelle
3        Ryan
4        Gary
5        Nina
6       Simon
7        Guru
Name: name, dtype: object

In [14]:
missing_values=['n/a','',' ','--']
df=pd.read_csv('emp.csv',na_values = missing_values)

In [21]:
df['id'].replace({1:0,6:0})

0    0.0
1    2.0
2    3.0
3    4.0
4    NaN
5    0.0
6    7.0
7    8.0
Name: id, dtype: float64

In [15]:
df.head()

    id      name  salary  start_date        dept
0  1.0      Rick  623.30  01-01-2012          IT
1  2.0       Dan  515.20  23-09-2013  Operations
2  3.0  Michelle     NaN  15-11-2014          IT
3  4.0      Ryan  729.00  11-05-2014          HR
4  NaN      Gary  843.25  27-03-2015     Finance

In [ ]:
#dropping of single column
df=pd.read_csv('emp.csv')
df.head()

In [ ]:
#dropping of columns
df.drop(columns=['id'])

In [ ]:
#deleting of specific rows
df.drop([0,1])

In [22]:
df=pd.read_csv("emp.csv")
df.head()
x=df['salary']
print(x)

0     623.30
1     515.20
2        NaN
3     729.00
4     843.25
5    8478.00
6    1032.80
7     922.50
Name: salary, dtype: float64

In [23]:
x=x.dropna()

In [28]:
degree = ["low", "medium","high"]

#equi width binning
categorical_object = pd.cut(x, 3,labels=degree)
print(categorical_object)

#equi frequency binning
categorical_object2=pd.qcut(x,3,labels=degree)
print(categorical_object2)

0     low
1     low
3     low
4     low
5    high
6     low
7     low
Name: salary, dtype: category
Categories (3, object): [low < medium < high]
0       low
1       low
3       low
4    medium
5      high
6      high
7    medium
Name: salary, dtype: category
Categories (3, object): [low < medium < high]

In [27]:
pd.value_counts(categorical_object)

low       6
high      1
medium    0
Name: salary, dtype: int64

In [29]:
pd.value_counts(categorical_object2)

low       3
high      2
medium    2
Name: salary, dtype: int64

In [1]:
# Principal Component Analysis
# Pre processing to apply PCA
from sklearn.decomposition import PCA
from sklearn import preprocessing
import matplotlib.pyplot as plt

In [28]:
import pandas as pd
df=pd.read_csv('Housing.csv') 
df.head()

,Unnamed: 0,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,1,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,2,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,3,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,4,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,5,61000.0,6360,2,1,1,yes,no,no,no,no,0,no

In [29]:
from sklearn import decomposition
pca = decomposition.PCA(n_components=1)
x=df[['lotsize','bedrooms','bathrms','stories','garagepl']]
principalComponents = pca.fit_transform(x)
print(principalComponents)

[[ 6.99734462e+02]
 [-1.15026574e+03]
 [-2.09026568e+03]
 [ 1.49973431e+03]
 [ 1.20973423e+03]
 [-9.90265690e+02]
 [-1.27026533e+03]
 [-9.90265623e+02]
 [-3.50265698e+02]
 [ 3.49734578e+02]
 [ 2.04973474e+03]
 [-2.15026573e+03]
 [-3.45026563e+03]
 [-2.27026567e+03]
 [-1.55026573e+03]
 [-1.96526573e+03]
 [-1.85026551e+03]
 [ 4.97344151e+01]
 [-1.70026578e+03]
 [-1.16426555e+03]
 [-3.65265525e+02]
 [-6.40265565e+02]
 [-1.15026565e+03]
 [-1.21626574e+03]
 [-1.90265752e+02]
 [-2.15026569e+03]
 [-1.35026574e+03]
 [-1.90265752e+02]
 [-2.15026568e+03]
 [-6.50265661e+02]
 [-1.65026573e+03]
 [-1.65026532e+03]
 [-1.15026574e+03]
 [-6.50265746e+02]
 [ 1.20973426e+03]
 [-6.50265466e+02]
 [-1.11826574e+03]
 [ 1.97343974e+01]
 [ 2.49734704e+02]
 [-2.00026568e+03]
 [-1.40526565e+03]
 [-6.30265661e+02]
 [-5.10265471e+02]
 [ 3.42973476e+03]
 [-3.15026568e+03]
 [-2.99026563e+03]
 [-2.11026573e+03]
 [-2.06026564e+03]
 [-1.90265582e+02]
 [-1.80026565e+03]
 [ 1.49734477e+02]
 [-1.05026564e+03]
 [ 4.01573447e+03]
 [-1.11026552e+03]
 [-1.52026556e+03]
 [-1.53026574e+03]
 [-2.75026567e+03]
 [ 2.10973474e+03]
 [-7.50265660e+02]
 [-2.75026563e+03]
 [-1.03026571e+03]
 [-4.00265749e+02]
 [-8.70265463e+02]
 [-3.30265665e+02]
 [ 3.49734378e+02]
 [ 3.49734326e+02]
 [-1.10265668e+02]
 [ 8.49734375e+02]
 [-2.65026572e+03]
 [-1.05526566e+03]
 [-1.05526546e+03]
 [-2.00026564e+03]
 [-3.31426571e+03]
 [-2.67526564e+03]
 [-1.94026564e+03]
 [-1.97026568e+03]
 [-3.50026562e+03]
 [-1.97026559e+03]
 [-1.97026540e+03]
 [ 1.20973437e+03]
 [-9.10265658e+02]
 [-1.91026559e+03]
 [-1.50026565e+03]
 [-1.91026536e+03]
 [-1.37026570e+03]
 [ 1.32973445e+03]
 [ 6.99734517e+02]
 [-2.00026563e+03]
 [-2.15026559e+03]
 [-2.06026573e+03]
 [ 9.09734286e+02]
 [ 7.49734558e+02]
 [ 2.26973463e+03]
 [ 3.34973468e+03]
 [ 2.89973440e+03]
 [ 1.64973422e+03]
 [ 3.09973454e+03]
 [ 3.09973468e+03]
 [-1.65026573e+03]
 [-2.31526573e+03]
 [-6.50265616e+02]
 [-1.85026556e+03]
 [-8.30265378e+02]
 [-1.65026527e+03]
 [-1.58265342e+02]
 [-5.50265748e+02]
 [-1.43026574e+03]
 [-1.47026561e+03]
 [-2.15026560e+03]
 [-1.40026574e+03]
 [-7.42657020e+01]
 [-6.50265746e+02]
 [-1.50265667e+02]
 [-8.90265606e+02]
 [ 1.38973441e+03]
 [-1.45026560e+03]
 [-1.39026537e+03]
 [-1.15026547e+03]
 [-8.50265474e+02]
 [ 1.68973455e+03]
 [-7.50265605e+02]
 [ 5.34973450e+03]
 [-7.50265745e+02]
 [-3.10265525e+02]
 [-1.03026560e+03]
 [-8.90265562e+02]
 [ 8.09734550e+02]
 [ 3.64973461e+03]
 [-5.90265477e+02]
 [-5.50265337e+02]
 [-3.10265717e+02]
 [-1.30026565e+03]
 [-2.50265666e+02]
 [-1.30026541e+03]
 [-1.39026540e+03]
 [ 8.49734624e+02]
 [-7.80265659e+02]
 [ 2.54973421e+03]
 [-2.16026559e+03]
 [-1.40026565e+03]
 [-2.15026564e+03]
 [-2.50026550e+03]
 [-6.50265284e+02]
 [-6.50265746e+02]
 [-6.50265661e+02]
 [-6.50265573e+02]
 [-2.97526563e+03]
 [-6.50265443e+02]
 [-3.50265483e+02]
 [-5.50265611e+02]
 [-1.70026551e+03]
 [-2.15026564e+03]
 [-1.55026552e+03]
 [-1.55026551e+03]
 [-1.40026569e+03]
 [-2.54026550e+03]
 [-2.19726564e+03]
 [-2.40326554e+03]
 [-3.24526552e+03]
 [-1.18226565e+03]
 [-1.98826550e+03]
 [ 8.49734652e+02]
 [-2.24026567e+03]
 [-3.01526559e+03]
 [-2.03026564e+03]
 [-1.07526541e+03]
 [-1.74026565e+03]
 [-2.35026567e+03]
 [-2.46626558e+03]
 [-2.05026564e+03]
 [-1.52026574e+03]
 [-3.20026566e+03]
 [-2.72026567e+03]
 [-8.30265552e+02]
 [-2.11426564e+03]
 [-1.52026532e+03]
 [ 2.49734379e+02]
 [-1.73026527e+03]
 [-1.97026532e+03]
 [-1.49026560e+03]
 [-7.40265605e+02]
 [-1.16026565e+03]
 [-8.10265693e+02]
 [-1.64026565e+03]
 [-1.73026554e+03]
 [-1.73026556e+03]
 [ 3.44734293e+02]
 [-1.67026546e+03]
 [ 2.27373427e+03]
 [-1.69026560e+03]
 [-1.52026537e+03]
 [-1.52026574e+03]
 [-1.67026551e+03]
 [-1.69026550e+03]
 [-1.97026573e+03]
 [-1.51526574e+03]
 [-1.19026569e+03]
 [-8.00265519e+02]
 [-1.22026574e+03]
 [-1.58026565e+03]
 [-1.55026554e+03]
 [-2.63026538e+03]
 [-1.67026568e+03]
 [-1.97026555e+03]
 [-1.86026559e+03]
 [-1.15026556e+03]
 [-2.82526563e+03]
 [-8.00265744e+02]
 [-1.61026573e+03]
 [-1.19026541e+03]
 [-2.51026558e+03]
 [-2.45026572e+03]
 [-2.45026567e+03]
 [-1.97026564e+03]
 [-1.65026532e+03]
 [-1.52026574e+03]
 [ 8.49734742e+02]
 [-2.00026564e+03]
 [-1.35826560e+03]
 [-1.64026562e+03]
 [-2.03026564e+03]
 [-2.15026528e+03]
 [-9.50265517e+02]
 [-2.33326540e+03]
 [-1.91026542e+03]
 [-2.35026545e+03]
 [-1.33426546e+03]
 [-1.96526545e+03]
 [ 1.17073446e+03]
 [-1.50026533e+03]
 [-4.50265472e+02]
 [ 1.46473455e+03]
 [-1.30026565e+03]
 [-1.18026579e+03]
 [-2.15026569e+03]
 [-7.98265467e+02]
 [-1.52026518e+03]
 [-1.55026535e+03]
 [-2.15026545e+03]
 [-2.15026559e+03]
 [-2.36326554e+03]
 [-2.15026569e+03]
 [-3.80265698e+02]
 [-1.50126574e+03]
 [-1.18026565e+03]
 [-2.24026573e+03]
 [-1.67026559e+03]
 [ 1.46473431e+03]
 [-1.65026573e+03]
 [-1.70026565e+03]
 [-1.70026540e+03]
 [-1.63026569e+03]
 [ 1.77973450e+03]
 [-5.50265477e+02]
 [-7.90265608e+02]
 [-1.70026551e+03]
 [-7.40265238e+02]
 [-5.50265422e+02]
 [-1.51026574e+03]
 [ 8.49734235e+02]
 [ 2.49734379e+02]
 [-1.51026560e+03]
 [-1.51026574e+03]
 [-1.11026574e+03]
 [-1.51026560e+03]
 [-1.51026574e+03]
 [ 4.89734239e+02]
 [-1.55026573e+03]
 [-1.55026573e+03]
 [-5.18265611e+02]
 [-1.51026561e+03]
 [-2.50265718e+02]
 [-6.40265329e+02]
 [-1.05026570e+03]
 [-1.51026565e+03]
 [ 5.29734464e+02]
 [ 1.14973456e+03]
 [-1.15026551e+03]
 [-1.19026565e+03]
 [ 8.09734320e+02]
 [ 6.79734517e+02]
 [-6.50265318e+02]
 [-1.05026530e+03]
 [ 1.59973423e+03]
 [ 3.84973456e+03]
 [-2.60026564e+03]
 [ 2.00173431e+03]
 [ 1.29973437e+03]
 [-1.79026559e+03]
 [-1.88626573e+03]
 [-1.15026569e+03]
 [-1.15026551e+03]
 [-2.08126559e+03]
 [-1.11026574e+03]
 [-1.11026560e+03]
 [-1.96526545e+03]
 [ 7.49734376e+02]
 [-2.03026550e+03]
 [ 2.99734242e+02]
 [-1.11026574e+03]
 [-1.07026574e+03]
 [ 2.92973454e+03]
 [-1.11026557e+03]
 [-1.07026538e+03]
 [ 6.49734569e+02]
 [ 7.34734376e+02]
 [ 4.51673451e+03]
 [-1.73026555e+03]
 [ 6.49734237e+02]
 [ 2.44973463e+03]
 [ 2.49734714e+02]
 [-1.55265604e+02]
 [-2.15026564e+03]
 [ 3.49734338e+02]
 [ 1.29973433e+03]
 [ 1.05973444e+03]
 [-1.50265600e+02]
 [-1.50265634e+02]
 [ 6.77734441e+02]
 [ 4.97343635e+01]
 [ 3.49734500e+02]
 [ 1.19973439e+03]
 [ 3.09973437e+03]
 [ 8.49734426e+02]
 [ 2.54973459e+03]
 [ 3.72973447e+03]
 [ 3.72973434e+03]
 [ 1.32973471e+03]
 [ 1.84973470e+03]
 [ 3.72473439e+03]
 [ 2.00473460e+03]
 [ 3.80973496e+03]
 [ 2.19973436e+03]
 [-1.30026574e+03]
 [ 1.84973469e+03]
 [ 2.61973435e+03]
 [ 2.28973431e+03]
 [ 2.34973464e+03]
 [ 2.94973463e+03]
 [-1.25026565e+03]
 [-2.18026561e+03]
 [-2.15026564e+03]
 [ 5.34973432e+03]
 [ 3.49734511e+02]
 [-6.50265594e+02]
 [-1.30026569e+03]
 [-1.02026533e+03]
 [-1.10426552e+03]
 [-1.07126562e+03]
 [-1.15026537e+03]
 [ 4.70973424e+03]
 [ 1.84973431e+03]
 [ 2.82973454e+03]
 [ 1.64973450e+03]
 [-8.50265459e+02]
 [ 5.11873437e+03]
 [ 9.49734352e+02]
 [ 1.26973439e+03]
 [ 6.93973462e+03]
 [ 1.44973480e+03]
 [ 1.44973455e+03]
 [ 3.42973478e+03]
 [ 4.80973459e+03]
 [ 5.54973426e+03]
 [ 1.04497344e+04]
 [ 8.04973428e+03]
 [ 3.84973473e+03]
 [ 2.79973472e+03]
 [ 1.10497344e+04]
 [ 9.49734610e+02]
 [ 1.20973456e+03]
 [ 1.26973428e+03]
 [ 1.20973473e+03]
 [ 1.38973469e+03]
 [ 1.26973450e+03]
 [ 1.39973455e+03]
 [ 5.99734575e+02]
 [ 2.26973471e+03]
 [ 2.00973455e+03]
 [-1.15026561e+03]
 [ 3.84973459e+03]
 [ 1.39973431e+03]
 [ 8.04973451e+03]
 [ 1.93473455e+03]
 [ 1.44973441e+03]
 [ 1.74973427e+03]
 [ 6.30973456e+03]
 [ 1.86973455e+03]
 [ 1.38973456e+03]
 [ 2.84973454e+03]
 [ 4.46973452e+03]
 [ 5.34973441e+03]
 [-1.30265601e+02]
 [ 2.28973455e+03]
 [ 1.44973428e+03]
 [ 2.04973444e+03]
 [ 1.55973450e+03]
 [ 1.50973455e+03]
 [ 1.84973455e+03]
 [ 2.08073430e+03]
 [ 2.25973455e+03]
 [ 2.64973454e+03]
 [ 1.67473428e+03]
 [ 1.20973435e+03]
 [ 1.44973438e+03]
 [ 1.74973432e+03]
 [ 1.44973456e+03]
 [ 1.26973435e+03]
 [ 1.44973432e+03]
 [ 1.44973439e+03]
 [ 3.84973439e+03]
 [ 1.34973439e+03]
 [ 1.20973443e+03]
 [ 1.49734295e+02]
 [-2.30026560e+03]
 [ 1.24973442e+03]
 [ 6.02473436e+03]
 [ 1.59973451e+03]
 [ 2.34973482e+03]
 [ 8.49734460e+02]
 [ 5.08973446e+03]
 [-1.42656692e+01]
 [-1.75026537e+03]
 [-2.27026564e+03]
 [-1.31026551e+03]
 [-2.28026569e+03]
 [ 1.69734383e+02]
 [-1.63826559e+03]
 [-1.67026573e+03]
 [-1.55026568e+03]
 [-1.63026570e+03]
 [ 1.69734328e+02]
 [ 8.89734566e+02]
 [ 6.25973420e+03]
 [ 3.24973457e+03]
 [ 1.49734392e+02]
 [ 2.64973434e+03]
 [-1.63026565e+03]
 [ 2.09734608e+02]
 [ 1.71173459e+03]
 [-1.63026540e+03]
 [-1.10026571e+03]
 [-1.63026568e+03]
 [-7.50265328e+02]
 [ 5.69734272e+02]
 [ 6.28973444e+03]
 [ 2.33173452e+03]
 [ 3.49734563e+02]
 [-8.30265378e+02]
 [ 2.49734276e+02]
 [-8.30265692e+02]
 [-3.35265750e+02]
 [ 9.49734285e+02]
 [ 2.82973440e+03]
 [ 8.99734286e+02]
 [-1.35026551e+03]
 [ 2.49734431e+02]
 [ 8.49734432e+02]
 [-2.75226567e+03]
 [-3.00526563e+03]
 [-3.00526563e+03]
 [-3.00526560e+03]
 [-2.54026564e+03]
 [-3.20026558e+03]
 [-3.00526560e+03]
 [-2.87526560e+03]
 [-2.29426561e+03]
 [-3.13526563e+03]
 [-2.97426568e+03]
 [-3.00526557e+03]
 [-3.00526546e+03]
 [-2.36326567e+03]
 [ 4.34973470e+03]
 [-1.60265571e+02]
 [ 1.51973434e+03]
 [ 1.10373452e+03]
 [ 5.20973432e+03]
 [ 3.49734618e+02]
 [ 2.99734390e+02]
 [ 3.49734500e+02]
 [ 8.49734405e+02]
 [ 5.49734570e+02]
 [ 1.44973437e+03]
 [-1.15026574e+03]
 [-2.70265419e+02]
 [-2.70265429e+02]
 [ 2.89973421e+03]
 [ 2.94973435e+03]
 [ 7.29734428e+02]
 [ 7.29734236e+02]
 [ 7.79373420e+03]
 [ 8.69734286e+02]
 [-1.10026574e+03]
 [ 3.24973434e+03]
 [ 4.49734240e+02]
 [ 8.34734286e+02]
 [-6.50265695e+02]
 [-2.30265526e+02]
 [ 3.09973426e+03]
 [ 3.24973483e+03]
 [ 1.28973465e+03]
 [ 2.94973469e+03]
 [ 1.56973428e+03]
 [ 7.97734320e+02]
 [ 2.99973430e+03]
 [-3.50265750e+02]
 [ 4.64973465e+03]
 [ 3.36973453e+03]
 [ 3.22173460e+03]
 [-1.11026552e+03]
 [-5.04265383e+02]
 [-3.75265613e+02]
 [-2.00265615e+02]
 [-1.40265668e+02]
 [ 9.09734374e+02]
 [-1.56626573e+03]
 [ 8.49734398e+02]
 [ 8.49734483e+02]
 [ 1.08973455e+03]
 [ 8.49734505e+02]
 [ 2.52973460e+03]
 [ 8.49734624e+02]
 [ 8.49734624e+02]
 [ 8.49734764e+02]
 [ 8.49734624e+02]
 [ 2.32473469e+03]
 [-2.65277131e-01]
 [ 1.17473452e+03]
 [ 8.49734572e+02]
 [ 8.49734398e+02]
 [ 8.49734667e+02]
 [ 1.84973465e+03]
 [ 7.74973448e+03]
 [ 2.53573426e+03]
 [-1.50265634e+02]
 [ 6.49734434e+02]
 [ 8.49734432e+02]
 [-3.50265631e+02]
 [ 1.34973439e+03]
 [ 2.16973440e+03]
 [ 1.37473457e+03]
 [-3.50265553e+02]
 [ 8.49734432e+02]
 [ 8.49734572e+02]
 [ 8.49734505e+02]
 [ 8.49734460e+02]]

In [33]:
df['pca1']=principalComponents
x=df['pca1']
x=x.values
x=x.reshape(len(x),1)
print(x)

[[ 6.99734462e+02]
 [-1.15026574e+03]
 [-2.09026568e+03]
 [ 1.49973431e+03]
 [ 1.20973423e+03]
 [-9.90265690e+02]
 [-1.27026533e+03]
 [-9.90265623e+02]
 [-3.50265698e+02]
 [ 3.49734578e+02]
 [ 2.04973474e+03]
 [-2.15026573e+03]
 [-3.45026563e+03]
 [-2.27026567e+03]
 [-1.55026573e+03]
 [-1.96526573e+03]
 [-1.85026551e+03]
 [ 4.97344151e+01]
 [-1.70026578e+03]
 [-1.16426555e+03]
 [-3.65265525e+02]
 [-6.40265565e+02]
 [-1.15026565e+03]
 [-1.21626574e+03]
 [-1.90265752e+02]
 [-2.15026569e+03]
 [-1.35026574e+03]
 [-1.90265752e+02]
 [-2.15026568e+03]
 [-6.50265661e+02]
 [-1.65026573e+03]
 [-1.65026532e+03]
 [-1.15026574e+03]
 [-6.50265746e+02]
 [ 1.20973426e+03]
 [-6.50265466e+02]
 [-1.11826574e+03]
 [ 1.97343974e+01]
 [ 2.49734704e+02]
 [-2.00026568e+03]
 [-1.40526565e+03]
 [-6.30265661e+02]
 [-5.10265471e+02]
 [ 3.42973476e+03]
 [-3.15026568e+03]
 [-2.99026563e+03]
 [-2.11026573e+03]
 [-2.06026564e+03]
 [-1.90265582e+02]
 [-1.80026565e+03]
 [ 1.49734477e+02]
 [-1.05026564e+03]
 [ 4.01573447e+03]
 [-1.11026552e+03]
 [-1.52026556e+03]
 [-1.53026574e+03]
 [-2.75026567e+03]
 [ 2.10973474e+03]
 [-7.50265660e+02]
 [-2.75026563e+03]
 [-1.03026571e+03]
 [-4.00265749e+02]
 [-8.70265463e+02]
 [-3.30265665e+02]
 [ 3.49734378e+02]
 [ 3.49734326e+02]
 [-1.10265668e+02]
 [ 8.49734375e+02]
 [-2.65026572e+03]
 [-1.05526566e+03]
 [-1.05526546e+03]
 [-2.00026564e+03]
 [-3.31426571e+03]
 [-2.67526564e+03]
 [-1.94026564e+03]
 [-1.97026568e+03]
 [-3.50026562e+03]
 [-1.97026559e+03]
 [-1.97026540e+03]
 [ 1.20973437e+03]
 [-9.10265658e+02]
 [-1.91026559e+03]
 [-1.50026565e+03]
 [-1.91026536e+03]
 [-1.37026570e+03]
 [ 1.32973445e+03]
 [ 6.99734517e+02]
 [-2.00026563e+03]
 [-2.15026559e+03]
 [-2.06026573e+03]
 [ 9.09734286e+02]
 [ 7.49734558e+02]
 [ 2.26973463e+03]
 [ 3.34973468e+03]
 [ 2.89973440e+03]
 [ 1.64973422e+03]
 [ 3.09973454e+03]
 [ 3.09973468e+03]
 [-1.65026573e+03]
 [-2.31526573e+03]
 [-6.50265616e+02]
 [-1.85026556e+03]
 [-8.30265378e+02]
 [-1.65026527e+03]
 [-1.58265342e+02]
 [-5.50265748e+02]
 [-1.43026574e+03]
 [-1.47026561e+03]
 [-2.15026560e+03]
 [-1.40026574e+03]
 [-7.42657020e+01]
 [-6.50265746e+02]
 [-1.50265667e+02]
 [-8.90265606e+02]
 [ 1.38973441e+03]
 [-1.45026560e+03]
 [-1.39026537e+03]
 [-1.15026547e+03]
 [-8.50265474e+02]
 [ 1.68973455e+03]
 [-7.50265605e+02]
 [ 5.34973450e+03]
 [-7.50265745e+02]
 [-3.10265525e+02]
 [-1.03026560e+03]
 [-8.90265562e+02]
 [ 8.09734550e+02]
 [ 3.64973461e+03]
 [-5.90265477e+02]
 [-5.50265337e+02]
 [-3.10265717e+02]
 [-1.30026565e+03]
 [-2.50265666e+02]
 [-1.30026541e+03]
 [-1.39026540e+03]
 [ 8.49734624e+02]
 [-7.80265659e+02]
 [ 2.54973421e+03]
 [-2.16026559e+03]
 [-1.40026565e+03]
 [-2.15026564e+03]
 [-2.50026550e+03]
 [-6.50265284e+02]
 [-6.50265746e+02]
 [-6.50265661e+02]
 [-6.50265573e+02]
 [-2.97526563e+03]
 [-6.50265443e+02]
 [-3.50265483e+02]
 [-5.50265611e+02]
 [-1.70026551e+03]
 [-2.15026564e+03]
 [-1.55026552e+03]
 [-1.55026551e+03]
 [-1.40026569e+03]
 [-2.54026550e+03]
 [-2.19726564e+03]
 [-2.40326554e+03]
 [-3.24526552e+03]
 [-1.18226565e+03]
 [-1.98826550e+03]
 [ 8.49734652e+02]
 [-2.24026567e+03]
 [-3.01526559e+03]
 [-2.03026564e+03]
 [-1.07526541e+03]
 [-1.74026565e+03]
 [-2.35026567e+03]
 [-2.46626558e+03]
 [-2.05026564e+03]
 [-1.52026574e+03]
 [-3.20026566e+03]
 [-2.72026567e+03]
 [-8.30265552e+02]
 [-2.11426564e+03]
 [-1.52026532e+03]
 [ 2.49734379e+02]
 [-1.73026527e+03]
 [-1.97026532e+03]
 [-1.49026560e+03]
 [-7.40265605e+02]
 [-1.16026565e+03]
 [-8.10265693e+02]
 [-1.64026565e+03]
 [-1.73026554e+03]
 [-1.73026556e+03]
 [ 3.44734293e+02]
 [-1.67026546e+03]
 [ 2.27373427e+03]
 [-1.69026560e+03]
 [-1.52026537e+03]
 [-1.52026574e+03]
 [-1.67026551e+03]
 [-1.69026550e+03]
 [-1.97026573e+03]
 [-1.51526574e+03]
 [-1.19026569e+03]
 [-8.00265519e+02]
 [-1.22026574e+03]
 [-1.58026565e+03]
 [-1.55026554e+03]
 [-2.63026538e+03]
 [-1.67026568e+03]
 [-1.97026555e+03]
 [-1.86026559e+03]
 [-1.15026556e+03]
 [-2.82526563e+03]
 [-8.00265744e+02]
 [-1.61026573e+03]
 [-1.19026541e+03]
 [-2.51026558e+03]
 [-2.45026572e+03]
 [-2.45026567e+03]
 [-1.97026564e+03]
 [-1.65026532e+03]
 [-1.52026574e+03]
 [ 8.49734742e+02]
 [-2.00026564e+03]
 [-1.35826560e+03]
 [-1.64026562e+03]
 [-2.03026564e+03]
 [-2.15026528e+03]
 [-9.50265517e+02]
 [-2.33326540e+03]
 [-1.91026542e+03]
 [-2.35026545e+03]
 [-1.33426546e+03]
 [-1.96526545e+03]
 [ 1.17073446e+03]
 [-1.50026533e+03]
 [-4.50265472e+02]
 [ 1.46473455e+03]
 [-1.30026565e+03]
 [-1.18026579e+03]
 [-2.15026569e+03]
 [-7.98265467e+02]
 [-1.52026518e+03]
 [-1.55026535e+03]
 [-2.15026545e+03]
 [-2.15026559e+03]
 [-2.36326554e+03]
 [-2.15026569e+03]
 [-3.80265698e+02]
 [-1.50126574e+03]
 [-1.18026565e+03]
 [-2.24026573e+03]
 [-1.67026559e+03]
 [ 1.46473431e+03]
 [-1.65026573e+03]
 [-1.70026565e+03]
 [-1.70026540e+03]
 [-1.63026569e+03]
 [ 1.77973450e+03]
 [-5.50265477e+02]
 [-7.90265608e+02]
 [-1.70026551e+03]
 [-7.40265238e+02]
 [-5.50265422e+02]
 [-1.51026574e+03]
 [ 8.49734235e+02]
 [ 2.49734379e+02]
 [-1.51026560e+03]
 [-1.51026574e+03]
 [-1.11026574e+03]
 [-1.51026560e+03]
 [-1.51026574e+03]
 [ 4.89734239e+02]
 [-1.55026573e+03]
 [-1.55026573e+03]
 [-5.18265611e+02]
 [-1.51026561e+03]
 [-2.50265718e+02]
 [-6.40265329e+02]
 [-1.05026570e+03]
 [-1.51026565e+03]
 [ 5.29734464e+02]
 [ 1.14973456e+03]
 [-1.15026551e+03]
 [-1.19026565e+03]
 [ 8.09734320e+02]
 [ 6.79734517e+02]
 [-6.50265318e+02]
 [-1.05026530e+03]
 [ 1.59973423e+03]
 [ 3.84973456e+03]
 [-2.60026564e+03]
 [ 2.00173431e+03]
 [ 1.29973437e+03]
 [-1.79026559e+03]
 [-1.88626573e+03]
 [-1.15026569e+03]
 [-1.15026551e+03]
 [-2.08126559e+03]
 [-1.11026574e+03]
 [-1.11026560e+03]
 [-1.96526545e+03]
 [ 7.49734376e+02]
 [-2.03026550e+03]
 [ 2.99734242e+02]
 [-1.11026574e+03]
 [-1.07026574e+03]
 [ 2.92973454e+03]
 [-1.11026557e+03]
 [-1.07026538e+03]
 [ 6.49734569e+02]
 [ 7.34734376e+02]
 [ 4.51673451e+03]
 [-1.73026555e+03]
 [ 6.49734237e+02]
 [ 2.44973463e+03]
 [ 2.49734714e+02]
 [-1.55265604e+02]
 [-2.15026564e+03]
 [ 3.49734338e+02]
 [ 1.29973433e+03]
 [ 1.05973444e+03]
 [-1.50265600e+02]
 [-1.50265634e+02]
 [ 6.77734441e+02]
 [ 4.97343635e+01]
 [ 3.49734500e+02]
 [ 1.19973439e+03]
 [ 3.09973437e+03]
 [ 8.49734426e+02]
 [ 2.54973459e+03]
 [ 3.72973447e+03]
 [ 3.72973434e+03]
 [ 1.32973471e+03]
 [ 1.84973470e+03]
 [ 3.72473439e+03]
 [ 2.00473460e+03]
 [ 3.80973496e+03]
 [ 2.19973436e+03]
 [-1.30026574e+03]
 [ 1.84973469e+03]
 [ 2.61973435e+03]
 [ 2.28973431e+03]
 [ 2.34973464e+03]
 [ 2.94973463e+03]
 [-1.25026565e+03]
 [-2.18026561e+03]
 [-2.15026564e+03]
 [ 5.34973432e+03]
 [ 3.49734511e+02]
 [-6.50265594e+02]
 [-1.30026569e+03]
 [-1.02026533e+03]
 [-1.10426552e+03]
 [-1.07126562e+03]
 [-1.15026537e+03]
 [ 4.70973424e+03]
 [ 1.84973431e+03]
 [ 2.82973454e+03]
 [ 1.64973450e+03]
 [-8.50265459e+02]
 [ 5.11873437e+03]
 [ 9.49734352e+02]
 [ 1.26973439e+03]
 [ 6.93973462e+03]
 [ 1.44973480e+03]
 [ 1.44973455e+03]
 [ 3.42973478e+03]
 [ 4.80973459e+03]
 [ 5.54973426e+03]
 [ 1.04497344e+04]
 [ 8.04973428e+03]
 [ 3.84973473e+03]
 [ 2.79973472e+03]
 [ 1.10497344e+04]
 [ 9.49734610e+02]
 [ 1.20973456e+03]
 [ 1.26973428e+03]
 [ 1.20973473e+03]
 [ 1.38973469e+03]
 [ 1.26973450e+03]
 [ 1.39973455e+03]
 [ 5.99734575e+02]
 [ 2.26973471e+03]
 [ 2.00973455e+03]
 [-1.15026561e+03]
 [ 3.84973459e+03]
 [ 1.39973431e+03]
 [ 8.04973451e+03]
 [ 1.93473455e+03]
 [ 1.44973441e+03]
 [ 1.74973427e+03]
 [ 6.30973456e+03]
 [ 1.86973455e+03]
 [ 1.38973456e+03]
 [ 2.84973454e+03]
 [ 4.46973452e+03]
 [ 5.34973441e+03]
 [-1.30265601e+02]
 [ 2.28973455e+03]
 [ 1.44973428e+03]
 [ 2.04973444e+03]
 [ 1.55973450e+03]
 [ 1.50973455e+03]
 [ 1.84973455e+03]
 [ 2.08073430e+03]
 [ 2.25973455e+03]
 [ 2.64973454e+03]
 [ 1.67473428e+03]
 [ 1.20973435e+03]
 [ 1.44973438e+03]
 [ 1.74973432e+03]
 [ 1.44973456e+03]
 [ 1.26973435e+03]
 [ 1.44973432e+03]
 [ 1.44973439e+03]
 [ 3.84973439e+03]
 [ 1.34973439e+03]
 [ 1.20973443e+03]
 [ 1.49734295e+02]
 [-2.30026560e+03]
 [ 1.24973442e+03]
 [ 6.02473436e+03]
 [ 1.59973451e+03]
 [ 2.34973482e+03]
 [ 8.49734460e+02]
 [ 5.08973446e+03]
 [-1.42656692e+01]
 [-1.75026537e+03]
 [-2.27026564e+03]
 [-1.31026551e+03]
 [-2.28026569e+03]
 [ 1.69734383e+02]
 [-1.63826559e+03]
 [-1.67026573e+03]
 [-1.55026568e+03]
 [-1.63026570e+03]
 [ 1.69734328e+02]
 [ 8.89734566e+02]
 [ 6.25973420e+03]
 [ 3.24973457e+03]
 [ 1.49734392e+02]
 [ 2.64973434e+03]
 [-1.63026565e+03]
 [ 2.09734608e+02]
 [ 1.71173459e+03]
 [-1.63026540e+03]
 [-1.10026571e+03]
 [-1.63026568e+03]
 [-7.50265328e+02]
 [ 5.69734272e+02]
 [ 6.28973444e+03]
 [ 2.33173452e+03]
 [ 3.49734563e+02]
 [-8.30265378e+02]
 [ 2.49734276e+02]
 [-8.30265692e+02]
 [-3.35265750e+02]
 [ 9.49734285e+02]
 [ 2.82973440e+03]
 [ 8.99734286e+02]
 [-1.35026551e+03]
 [ 2.49734431e+02]
 [ 8.49734432e+02]
 [-2.75226567e+03]
 [-3.00526563e+03]
 [-3.00526563e+03]
 [-3.00526560e+03]
 [-2.54026564e+03]
 [-3.20026558e+03]
 [-3.00526560e+03]
 [-2.87526560e+03]
 [-2.29426561e+03]
 [-3.13526563e+03]
 [-2.97426568e+03]
 [-3.00526557e+03]
 [-3.00526546e+03]
 [-2.36326567e+03]
 [ 4.34973470e+03]
 [-1.60265571e+02]
 [ 1.51973434e+03]
 [ 1.10373452e+03]
 [ 5.20973432e+03]
 [ 3.49734618e+02]
 [ 2.99734390e+02]
 [ 3.49734500e+02]
 [ 8.49734405e+02]
 [ 5.49734570e+02]
 [ 1.44973437e+03]
 [-1.15026574e+03]
 [-2.70265419e+02]
 [-2.70265429e+02]
 [ 2.89973421e+03]
 [ 2.94973435e+03]
 [ 7.29734428e+02]
 [ 7.29734236e+02]
 [ 7.79373420e+03]
 [ 8.69734286e+02]
 [-1.10026574e+03]
 [ 3.24973434e+03]
 [ 4.49734240e+02]
 [ 8.34734286e+02]
 [-6.50265695e+02]
 [-2.30265526e+02]
 [ 3.09973426e+03]
 [ 3.24973483e+03]
 [ 1.28973465e+03]
 [ 2.94973469e+03]
 [ 1.56973428e+03]
 [ 7.97734320e+02]
 [ 2.99973430e+03]
 [-3.50265750e+02]
 [ 4.64973465e+03]
 [ 3.36973453e+03]
 [ 3.22173460e+03]
 [-1.11026552e+03]
 [-5.04265383e+02]
 [-3.75265613e+02]
 [-2.00265615e+02]
 [-1.40265668e+02]
 [ 9.09734374e+02]
 [-1.56626573e+03]
 [ 8.49734398e+02]
 [ 8.49734483e+02]
 [ 1.08973455e+03]
 [ 8.49734505e+02]
 [ 2.52973460e+03]
 [ 8.49734624e+02]
 [ 8.49734624e+02]
 [ 8.49734764e+02]
 [ 8.49734624e+02]
 [ 2.32473469e+03]
 [-2.65277131e-01]
 [ 1.17473452e+03]
 [ 8.49734572e+02]
 [ 8.49734398e+02]
 [ 8.49734667e+02]
 [ 1.84973465e+03]
 [ 7.74973448e+03]
 [ 2.53573426e+03]
 [-1.50265634e+02]
 [ 6.49734434e+02]
 [ 8.49734432e+02]
 [-3.50265631e+02]
 [ 1.34973439e+03]
 [ 2.16973440e+03]
 [ 1.37473457e+03]
 [-3.50265553e+02]
 [ 8.49734432e+02]
 [ 8.49734572e+02]
 [ 8.49734505e+02]
 [ 8.49734460e+02]]

In [30]:
df.drop(columns=['lotsize','bedrooms','bathrms','stories','garagepl'])

     Unnamed: 0     price driveway recroom fullbase gashw airco prefarea
0             1   42000.0      yes      no      yes    no    no       no
1             2   38500.0      yes      no       no    no    no       no
2             3   49500.0      yes      no       no    no    no       no
3             4   60500.0      yes     yes       no    no    no       no
4             5   61000.0      yes      no       no    no    no       no
5             6   66000.0      yes     yes      yes    no   yes       no
6             7   66000.0      yes      no      yes    no    no       no
7             8   69000.0      yes      no       no    no    no       no
8             9   83800.0      yes     yes      yes    no    no       no
9            10   88500.0      yes     yes       no    no   yes       no
10           11   90000.0      yes      no      yes    no   yes       no
11           12   30500.0       no      no       no    no    no       no
12           13   27000.0      yes      no       no    no    no       no
13           14   36000.0       no      no       no    no    no       no
14           15   37000.0      yes      no       no    no    no       no
15           16   37900.0      yes      no       no    no   yes       no
16           17   40500.0       no      no       no    no    no       no
17           18   40750.0      yes      no       no    no    no       no
18           19   45000.0      yes      no       no    no    no       no
19           20   45000.0       no     yes      yes    no    no       no
20           21   48500.0      yes     yes      yes    no   yes       no
21           22   65900.0      yes      no      yes    no    no       no
22           23   37900.0      yes      no       no    no   yes       no
23           24   38000.0      yes      no       no    no    no       no
24           25   42000.0      yes      no       no    no    no       no
25           26   42300.0      yes      no       no    no    no       no
26           27   43500.0      yes      no       no    no    no       no
27           28   44000.0      yes      no      yes    no   yes       no
28           29   44500.0       no      no       no    no   yes       no
29           30   44900.0      yes      no       no    no   yes       no
..          ...       ...      ...     ...      ...   ...   ...      ...
516         517   95000.0      yes     yes       no    no   yes       no
517         518   96500.0      yes      no       no    no   yes       no
518         519  101000.0      yes      no       no    no   yes       no
519         520  102000.0      yes     yes       no    no    no       no
520         521  103000.0      yes     yes       no    no   yes       no
521         522  105000.0      yes     yes       no    no   yes       no
522         523  108000.0      yes      no       no    no   yes       no
523         524  110000.0      yes      no       no    no    no       no
524         525  113000.0      yes      no       no    no   yes       no
525         526  120000.0      yes      no       no    no   yes       no
526         527  105000.0      yes      no       no    no   yes       no
527         528  106000.0      yes      no       no    no   yes       no
528         529  107500.0      yes      no       no    no   yes       no
529         530  108000.0      yes      no       no    no   yes       no
530         531  113750.0      yes     yes       no    no   yes       no
531         532  120000.0      yes      no       no    no   yes       no
532         533   70000.0      yes      no       no    no    no       no
533         534   71000.0      yes     yes      yes   yes    no       no
534         535   82000.0      yes      no       no    no   yes       no
535         536   82000.0      yes      no       no    no   yes       no
536         537   82500.0      yes      no       no    no   yes       no
537         538   83000.0      yes      no       no    no   yes       no
538         539   84000.0      yes      no       no    no   yes       no
539         540   85000.0      yes      no       no    no    no       no
540         541   85000.0      yes      no       no    no    no       no
541         542   91500.0      yes     yes       no    no   yes       no
542         543   94000.0      yes      no       no    no   yes       no
543         544  103000.0      yes     yes       no    no   yes       no
544         545  105000.0      yes     yes       no    no   yes       no
545         546  105000.0      yes      no       no    no   yes       no

[546 rows x 8 columns]

In [31]:
y=df[['price']]
y=y.values
y=y.reshape(len(y),1)
print(y)

[[ 42000.]
 [ 38500.]
 [ 49500.]
 [ 60500.]
 [ 61000.]
 [ 66000.]
 [ 66000.]
 [ 69000.]
 [ 83800.]
 [ 88500.]
 [ 90000.]
 [ 30500.]
 [ 27000.]
 [ 36000.]
 [ 37000.]
 [ 37900.]
 [ 40500.]
 [ 40750.]
 [ 45000.]
 [ 45000.]
 [ 48500.]
 [ 65900.]
 [ 37900.]
 [ 38000.]
 [ 42000.]
 [ 42300.]
 [ 43500.]
 [ 44000.]
 [ 44500.]
 [ 44900.]
 [ 45000.]
 [ 48000.]
 [ 49000.]
 [ 51500.]
 [ 61000.]
 [ 61000.]
 [ 61700.]
 [ 67000.]
 [ 82000.]
 [ 54500.]
 [ 66500.]
 [ 70000.]
 [ 82000.]
 [ 92000.]
 [ 38000.]
 [ 44000.]
 [ 41000.]
 [ 43000.]
 [ 48000.]
 [ 54800.]
 [ 55000.]
 [ 57000.]
 [ 68000.]
 [ 95000.]
 [ 38000.]
 [ 25000.]
 [ 25245.]
 [ 56000.]
 [ 35500.]
 [ 30000.]
 [ 48000.]
 [ 48000.]
 [ 52000.]
 [ 54000.]
 [ 56000.]
 [ 60000.]
 [ 60000.]
 [ 67000.]
 [ 47000.]
 [ 70000.]
 [ 45000.]
 [ 51000.]
 [ 32500.]
 [ 34000.]
 [ 35000.]
 [ 36000.]
 [ 45000.]
 [ 47000.]
 [ 55000.]
 [ 63900.]
 [ 50000.]
 [ 35000.]
 [ 50000.]
 [ 43000.]
 [ 55500.]
 [ 57000.]
 [ 60000.]
 [ 78000.]
 [ 35000.]
 [ 44000.]
 [ 47000.]
 [ 58000.]
 [163000.]
 [128000.]
 [123500.]
 [ 39000.]
 [ 53900.]
 [ 59900.]
 [ 35000.]
 [ 43000.]
 [ 57000.]
 [ 79000.]
 [125000.]
 [132000.]
 [ 58000.]
 [ 43000.]
 [ 48000.]
 [ 58500.]
 [ 73000.]
 [ 63500.]
 [ 43000.]
 [ 46500.]
 [ 92000.]
 [ 75000.]
 [ 75000.]
 [ 85000.]
 [ 93000.]
 [ 94500.]
 [106500.]
 [116000.]
 [ 61500.]
 [ 80000.]
 [ 37000.]
 [ 59500.]
 [ 70000.]
 [ 95000.]
 [117000.]
 [122500.]
 [123500.]
 [127000.]
 [ 35000.]
 [ 44500.]
 [ 49900.]
 [ 50500.]
 [ 65000.]
 [ 90000.]
 [ 46000.]
 [ 35000.]
 [ 26500.]
 [ 43000.]
 [ 56000.]
 [ 40000.]
 [ 51000.]
 [ 51000.]
 [ 57250.]
 [ 44000.]
 [ 61000.]
 [ 62000.]
 [ 80000.]
 [ 50000.]
 [ 59900.]
 [ 35500.]
 [ 37000.]
 [ 42000.]
 [ 48000.]
 [ 60000.]
 [ 60000.]
 [ 60000.]
 [ 62000.]
 [ 63000.]
 [ 63900.]
 [130000.]
 [ 25000.]
 [ 50000.]
 [ 52900.]
 [ 62000.]
 [ 73500.]
 [ 38000.]
 [ 46000.]
 [ 48000.]
 [ 52500.]
 [ 32000.]
 [ 38000.]
 [ 46000.]
 [ 50000.]
 [ 57500.]
 [ 70000.]
 [ 69900.]
 [ 74500.]
 [ 42000.]
 [ 60000.]
 [ 50000.]
 [ 58000.]
 [ 63900.]
 [ 28000.]
 [ 54000.]
 [ 44700.]
 [ 47000.]
 [ 50000.]
 [ 57250.]
 [ 67000.]
 [ 52500.]
 [ 42000.]
 [ 57500.]
 [ 33000.]
 [ 34400.]
 [ 40000.]
 [ 40500.]
 [ 46500.]
 [ 52000.]
 [ 53000.]
 [ 53900.]
 [ 50000.]
 [ 55500.]
 [ 56000.]
 [ 60000.]
 [ 60000.]
 [ 69500.]
 [ 72000.]
 [ 92500.]
 [ 40500.]
 [ 42000.]
 [ 47900.]
 [ 52000.]
 [ 62000.]
 [ 41000.]
 [138300.]
 [ 42000.]
 [ 47000.]
 [ 64500.]
 [ 46000.]
 [ 58000.]
 [ 70100.]
 [ 78500.]
 [ 87250.]
 [ 70800.]
 [ 56000.]
 [ 48000.]
 [ 68000.]
 [ 79000.]
 [ 80000.]
 [ 87000.]
 [ 25000.]
 [ 32500.]
 [ 36000.]
 [ 42500.]
 [ 43000.]
 [ 50000.]
 [ 26000.]
 [ 30000.]
 [ 34000.]
 [ 52000.]
 [ 70000.]
 [ 27000.]
 [ 32500.]
 [ 37200.]
 [ 38000.]
 [ 42000.]
 [ 44500.]
 [ 45000.]
 [ 48500.]
 [ 52000.]
 [ 53900.]
 [ 60000.]
 [ 61000.]
 [ 64500.]
 [ 71000.]
 [ 75500.]
 [ 33500.]
 [ 41000.]
 [ 41000.]
 [ 46200.]
 [ 48500.]
 [ 48900.]
 [ 50000.]
 [ 51000.]
 [ 52500.]
 [ 52500.]
 [ 54000.]
 [ 59000.]
 [ 60000.]
 [ 63000.]
 [ 64000.]
 [ 64900.]
 [ 65000.]
 [ 66000.]
 [ 70000.]
 [ 65500.]
 [ 57000.]
 [ 52000.]
 [ 54000.]
 [ 74500.]
 [ 90000.]
 [ 45000.]
 [ 45000.]
 [ 65000.]
 [ 55000.]
 [ 62000.]
 [ 30000.]
 [ 34000.]
 [ 38000.]
 [ 39000.]
 [ 45000.]
 [ 47000.]
 [ 47500.]
 [ 49000.]
 [ 50000.]
 [ 50000.]
 [ 52900.]
 [ 53000.]
 [ 55000.]
 [ 56000.]
 [ 58500.]
 [ 59500.]
 [ 60000.]
 [ 64000.]
 [ 67000.]
 [ 68100.]
 [ 70000.]
 [ 72000.]
 [ 57500.]
 [ 69900.]
 [ 70000.]
 [ 75000.]
 [ 76900.]
 [ 78000.]
 [ 80000.]
 [ 82000.]
 [ 83000.]
 [ 83000.]
 [ 83900.]
 [ 88500.]
 [ 93000.]
 [ 98000.]
 [ 98500.]
 [ 99000.]
 [101000.]
 [110000.]
 [115442.]
 [120000.]
 [124000.]
 [175000.]
 [ 50000.]
 [ 55000.]
 [ 60000.]
 [ 61000.]
 [106000.]
 [155000.]
 [141000.]
 [ 62500.]
 [ 70000.]
 [ 73000.]
 [ 80000.]
 [ 80000.]
 [ 88000.]
 [ 49000.]
 [ 52000.]
 [ 59500.]
 [ 60000.]
 [ 64000.]
 [ 64500.]
 [ 68500.]
 [ 78500.]
 [ 86000.]
 [ 86900.]
 [ 75000.]
 [ 78000.]
 [ 95000.]
 [ 97000.]
 [107000.]
 [130000.]
 [145000.]
 [175000.]
 [ 72000.]
 [ 84900.]
 [ 99000.]
 [114000.]
 [120000.]
 [145000.]
 [ 79000.]
 [ 82000.]
 [ 85000.]
 [100500.]
 [122000.]
 [126500.]
 [133000.]
 [140000.]
 [190000.]
 [ 84000.]
 [ 97000.]
 [103500.]
 [112500.]
 [140000.]
 [ 74700.]
 [ 78000.]
 [ 78900.]
 [ 83900.]
 [ 85000.]
 [ 85000.]
 [ 86000.]
 [ 86900.]
 [ 94500.]
 [ 96000.]
 [106000.]
 [ 72000.]
 [ 74500.]
 [ 77000.]
 [ 80750.]
 [ 82900.]
 [ 85000.]
 [ 92500.]
 [ 76000.]
 [ 77500.]
 [ 80000.]
 [ 80000.]
 [ 86000.]
 [ 87000.]
 [ 87500.]
 [ 89000.]
 [ 89900.]
 [ 90000.]
 [ 95000.]
 [112000.]
 [ 31900.]
 [ 52000.]
 [ 90000.]
 [100000.]
 [ 91700.]
 [174500.]
 [ 94700.]
 [ 68000.]
 [ 80000.]
 [ 61100.]
 [ 62900.]
 [ 65500.]
 [ 66000.]
 [ 49500.]
 [ 50000.]
 [ 53500.]
 [ 58550.]
 [ 64500.]
 [ 65000.]
 [ 69000.]
 [ 73000.]
 [ 75000.]
 [ 75000.]
 [132000.]
 [ 60000.]
 [ 65000.]
 [ 69000.]
 [ 51900.]
 [ 57000.]
 [ 65000.]
 [ 79500.]
 [ 72500.]
 [104900.]
 [114900.]
 [120000.]
 [ 58000.]
 [ 67000.]
 [ 67000.]
 [ 69000.]
 [ 73000.]
 [ 73500.]
 [ 74900.]
 [ 75000.]
 [ 79500.]
 [120900.]
 [ 44555.]
 [ 47000.]
 [ 47600.]
 [ 49000.]
 [ 49000.]
 [ 49000.]
 [ 49500.]
 [ 52000.]
 [ 54000.]
 [ 55000.]
 [ 55000.]
 [ 56000.]
 [ 60000.]
 [ 60500.]
 [ 50000.]
 [ 64900.]
 [ 93000.]
 [ 85000.]
 [ 61500.]
 [ 88500.]
 [ 88000.]
 [ 89000.]
 [ 89500.]
 [ 95000.]
 [ 95500.]
 [ 51500.]
 [ 62900.]
 [118500.]
 [ 42900.]
 [ 44100.]
 [ 47000.]
 [ 50000.]
 [ 50000.]
 [ 53000.]
 [ 53000.]
 [ 54000.]
 [ 58500.]
 [ 59000.]
 [ 60000.]
 [ 62900.]
 [ 64000.]
 [ 65000.]
 [ 67900.]
 [ 68500.]
 [ 70000.]
 [ 70500.]
 [ 71500.]
 [ 71900.]
 [ 75000.]
 [ 75000.]
 [ 87000.]
 [ 64000.]
 [ 70000.]
 [ 47500.]
 [ 62600.]
 [ 66000.]
 [ 58900.]
 [ 53000.]
 [ 95000.]
 [ 96500.]
 [101000.]
 [102000.]
 [103000.]
 [105000.]
 [108000.]
 [110000.]
 [113000.]
 [120000.]
 [105000.]
 [106000.]
 [107500.]
 [108000.]
 [113750.]
 [120000.]
 [ 70000.]
 [ 71000.]
 [ 82000.]
 [ 82000.]
 [ 82500.]
 [ 83000.]
 [ 84000.]
 [ 85000.]
 [ 85000.]
 [ 91500.]
 [ 94000.]
 [103000.]
 [105000.]
 [105000.]]

In [51]:
from sklearn import linear_model
lm = linear_model.LinearRegression()
lm.fit(x,y)
predictions = lm.predict(x)

In [53]:
print('Intercept: \n', lm.intercept_)
print('Coefficients: \n',lm.coef_)
print(predictions)

Intercept:
 [68121.5970696]
Coefficients:
 [[6.59876782]]
[[ 72738.98231581]
 [ 60531.26052614]
 [ 54328.41919957]
 [ 78017.99557579]
 [ 76104.35237184]
 [ 61587.06370392]
 [ 59739.41110654]
 [ 61587.06414612]
 [ 65810.27505191]
 [ 70429.41434832]
 [ 81647.32067813]
 [ 53932.49279491]
 [ 45354.0953062 ]
 [ 53140.64100795]
 [ 57891.75343365]
 [ 55153.26482518]
 [ 55912.12460118]
 [ 68449.78292739]
 [ 56901.93793317]
 [ 60438.87899915]
 [ 65711.29468205]
 [ 63896.63326798]
 [ 60531.26108803]
 [ 60095.74185588]
 [ 66866.07754812]
 [ 53932.49301601]
 [ 59211.50697989]
 [ 66866.07754812]
 [ 53932.4931357 ]
 [ 63830.64495364]
 [ 57231.87666052]
 [ 57231.87941322]
 [ 60531.26052614]
 [ 63830.64439175]
 [ 76104.35259294]
 [ 63830.64624177]
 [ 60742.42109354]
 [ 68251.81977577]
 [ 69769.5383988 ]
 [ 54922.30825083]
 [ 58848.57531656]
 [ 63962.62030827]
 [ 64754.47370181]
 [ 90753.62042114]
 [ 47333.72528478]
 [ 48389.52846256]
 [ 54196.44350416]
 [ 54526.38245261]
 [ 66866.0786719 ]
 [ 56242.06206273]
 [ 69109.66011645]
 [ 61191.13798084]
 [ 94620.49647569]
 [ 60795.21272229]
 [ 58089.71761995]
 [ 58023.72878827]
 [ 49973.23249696]
 [ 82043.24674201]
 [ 63170.76818052]
 [ 49973.23271806]
 [ 61323.11287499]
 [ 65480.33632456]
 [ 62378.9173409 ]
 [ 65942.25062764]
 [ 70429.41302566]
 [ 70429.41268487]
 [ 67393.97952851]
 [ 73728.79691361]
 [ 50633.10892929]
 [ 61158.14402249]
 [ 61158.14531062]
 [ 54922.30851648]
 [ 46251.52715576]
 [ 50468.1402979 ]
 [ 55318.23458036]
 [ 55120.27132732]
 [ 45024.15691964]
 [ 55120.27188921]
 [ 55120.27313279]
 [ 76104.35329685]
 [ 62114.96534352]
 [ 55516.19797541]
 [ 58221.6923821 ]
 [ 55516.19946231]
 [ 59079.53184637]
 [ 76896.20598649]
 [ 72738.98267893]
 [ 54922.30859162]
 [ 53932.49371992]
 [ 54526.38189072]
 [ 74124.72239326]
 [ 73068.9213394 ]
 [ 83099.04891965]
 [ 90225.71846702]
 [ 87256.27110342]
 [ 79007.81017358]
 [ 88576.02557468]
 [ 88576.02649969]
 [ 57231.87666052]
 [ 52843.69611925]
 [ 63830.64524988]
 [ 55912.12426864]
 [ 62642.86861204]
 [ 57231.87970946]
 [ 67077.24082367]
 [ 64490.52116488]
 [ 58683.60556139]
 [ 58419.65571027]
 [ 53932.49365304]
 [ 58881.56859333]
 [ 67631.53494573]
 [ 63830.64439175]
 [ 67130.02881926]
 [ 62246.94103894]
 [ 77292.13176238]
 [ 58551.63110945]
 [ 58947.55868255]
 [ 60531.26230928]
 [ 62510.89262864]
 [ 79271.76305131]
 [ 63170.76854364]
 [103423.25290306]
 [ 63170.76761863]
 [ 66074.22690727]
 [ 61323.1135789 ]
 [ 62246.94133518]
 [ 73464.84735873]
 [ 92205.34834419]
 [ 64226.57223876]
 [ 64490.52387302]
 [ 66074.22564147]
 [ 59541.44592834]
 [ 66470.15204613]
 [ 59541.44755726]
 [ 58947.55846145]
 [ 73728.79855473]
 [ 62972.80514858]
 [ 84946.70113169]
 [ 53866.5060426 ]
 [ 58881.56915522]
 [ 53932.4933568 ]
 [ 51622.92557588]
 [ 63830.64744069]
 [ 63830.64439175]
 [ 63830.64495364]
 [ 63830.64553786]
 [ 48488.50997853]
 [ 63830.64639599]
 [ 65810.27647193]
 [ 64490.52206756]
 [ 56901.93976086]
 [ 53932.4933568 ]
 [ 57891.75487599]
 [ 57891.75492055]
 [ 58881.56893412]
 [ 51358.97487488]
 [ 53622.35127343]
 [ 52263.00575782]
 [ 46706.84337268]
 [ 60320.10052063]
 [ 55001.49465427]
 [ 73728.7987413 ]
 [ 53338.60403989]
 [ 48224.55956552]
 [ 54724.34548454]
 [ 61026.17029679]
 [ 56637.9881266 ]
 [ 52612.73958945]
 [ 51847.28311685]
 [ 54592.37012992]
 [ 58089.71646558]
 [ 47003.78701791]
 [ 50171.1955289 ]
 [ 62642.86746593]
 [ 54170.04899512]
 [ 58089.71917373]
 [ 69769.53625254]
 [ 56703.97829096]
 [ 55120.27369468]
 [ 58287.6804002 ]
 [ 63236.75622095]
 [ 60465.27341072]
 [ 62774.84189555]
 [ 57297.86489972]
 [ 56703.97648549]
 [ 56703.97638813]
 [ 70396.41862512]
 [ 57099.90313359]
 [ 83125.44157866]
 [ 56967.92685395]
 [ 58089.71887749]
 [ 58089.71646558]
 [ 57099.9027928 ]
 [ 56967.92751331]
 [ 55120.27098653]
 [ 58122.71030424]
 [ 60267.31015768]
 [ 62840.83071897]
 [ 60069.34678495]
 [ 57693.7909636 ]
 [ 57891.75469945]
 [ 50765.08652753]
 [ 57099.90164669]
 [ 55120.27218545]
 [ 55846.13636197]
 [ 60531.26172506]
 [ 49478.32513822]
 [ 62840.82923207]
 [ 57495.82736977]
 [ 60267.3120077 ]
 [ 51556.93733667]
 [ 51952.86247554]
 [ 51952.86281633]
 [ 55120.27154842]
 [ 57231.87941322]
 [ 58089.71646558]
 [ 73728.79933377]
 [ 54922.30851648]
 [ 59158.71774072]
 [ 57297.86512082]
 [ 54724.34548454]
 [ 53932.49576871]
 [ 61851.01555928]
 [ 52724.92042402]
 [ 55516.19909919]
 [ 52612.7410318 ]
 [ 59317.08911361]
 [ 55153.2666752 ]
 [ 75847.00191722]
 [ 58221.69452835]
 [ 65150.39976569]
 [ 77787.04026723]
 [ 59541.44592834]
 [ 60333.29715341]
 [ 53932.49301601]
 [ 62854.02859522]
 [ 58089.72014329]
 [ 57891.75594292]
 [ 53932.49464493]
 [ 53932.49369759]
 [ 52526.95646707]
 [ 53932.49301601]
 [ 65612.31201998]
 [ 58215.09305248]
 [ 60333.29805609]
 [ 53338.6036991 ]
 [ 57099.90223091]
 [ 77787.0387052 ]
 [ 57231.87666052]
 [ 56901.93883585]
 [ 56901.94046477]
 [ 57363.85231139]
 [ 79865.65180633]
 [ 64490.52294801]
 [ 62906.81781206]
 [ 56901.93976086]
 [ 63236.75864112]
 [ 64490.52331113]
 [ 58155.70414289]
 [ 73728.7959886 ]
 [ 69769.53625254]
 [ 58155.70504557]
 [ 58155.70414289]
 [ 60795.21123539]
 [ 58155.7050679 ]
 [ 58155.70414289]
 [ 71353.23960536]
 [ 57891.75343365]
 [ 57891.75343365]
 [ 64701.68263496]
 [ 58155.70500102]
 [ 66470.15170534]
 [ 63896.63482176]
 [ 61191.1375955 ]
 [ 58155.70470478]
 [ 71617.1918015 ]
 [ 75708.42849878]
 [ 60531.26201304]
 [ 60267.31037878]
 [ 73464.84584124]
 [ 72607.00732431]
 [ 63830.64721959]
 [ 61191.14022851]
 [ 78677.87178702]
 [ 93525.1015942 ]
 [ 50963.04787774]
 [ 81330.57697687]
 [ 76698.24237033]
 [ 56308.05010316]
 [ 55674.56747595]
 [ 60531.26086693]
 [ 60531.26201304]
 [ 54387.80869337]
 [ 60795.21123539]
 [ 60795.2121604 ]
 [ 55153.2666752 ]
 [ 73068.92014049]
 [ 54724.34640955]
 [ 70099.47373642]
 [ 60795.21123539]
 [ 61059.16194464]
 [ 87454.23506037]
 [ 60795.2123815 ]
 [ 61059.16435655]
 [ 72409.04463316]
 [ 72969.93862452]
 [ 97926.47938295]
 [ 56703.97644094]
 [ 72409.04244235]
 [ 84286.82711127]
 [ 69769.53846568]
 [ 67097.03539653]
 [ 53932.4933568 ]
 [ 70429.41276001]
 [ 76698.24210468]
 [ 75114.53855704]
 [ 67130.02926146]
 [ 67130.02904036]
 [ 72593.80928371]
 [ 68449.7825866 ]
 [ 70429.41383098]
 [ 76038.36577376]
 [ 88576.02446309]
 [ 73728.7972544 ]
 [ 84946.70361874]
 [ 92733.24883768]
 [ 92733.24797955]
 [ 76896.20764994]
 [ 80327.56687018]
 [ 92700.25448169]
 [ 81350.37520522]
 [ 93261.15348166]
 [ 82637.13335077]
 [ 59541.44536645]
 [ 80327.56683565]
 [ 85408.61579789]
 [ 83231.0221586 ]
 [ 83626.95036873]
 [ 87586.21097688]
 [ 59871.3843149 ]
 [ 53734.53054596]
 [ 53932.4933568 ]
 [103423.25170414]
 [ 70429.41390612]
 [ 63830.64539584]
 [ 59541.44570724]
 [ 61389.10303935]
 [ 60834.80532867]
 [ 61052.56395989]
 [ 60531.26293805]
 [ 99200.03977194]
 [ 80327.56428172]
 [ 86794.35828724]
 [ 79007.8120236 ]
 [ 62510.89272601]
 [101898.93669902]
 [ 74388.67354471]
 [ 76500.27951494]
 [113915.29452073]
 [ 77688.06040646]
 [ 77688.05875126]
 [ 90753.62052255]
 [ 99859.91891242]
 [104743.00488727]
 [137076.96839922]
 [121239.92457847]
 [ 93525.10267343]
 [ 86596.39645423]
 [141036.22868309]
 [ 74388.67524877]
 [ 76104.35456265]
 [ 76500.27877651]
 [ 76104.35564188]
 [ 77292.1336124 ]
 [ 76500.28021885]
 [ 77358.1203647 ]
 [ 72079.10628113]
 [ 83099.04943698]
 [ 81383.36874764]
 [ 60531.26138427]
 [ 93525.10174842]
 [ 77358.11880267]
 [121239.92606537]
 [ 80888.46116779]
 [ 77688.05782625]
 [ 79667.6872875 ]
 [109758.07043413]
 [ 80459.54126526]
 [ 77292.13275427]
 [ 86926.33364187]
 [ 97616.33736646]
 [103423.25234117]
 [ 67262.00461608]
 [ 83231.02374691]
 [ 77688.05696813]
 [ 81647.31875297]
 [ 78413.92286091]
 [ 78083.98481514]
 [ 80327.56591064]
 [ 81851.87962763]
 [ 83033.06068044]
 [ 85606.58009562]
 [ 79172.77970765]
 [ 76104.35315483]
 [ 77688.05760515]
 [ 79667.68758373]
 [ 77688.05881815]
 [ 76500.27921871]
 [ 77688.05726436]
 [ 77688.05770656]
 [ 93525.10044809]
 [ 77028.18093344]
 [ 76104.35367217]
 [ 69109.65891753]
 [ 52942.67849335]
 [ 76368.30434689]
 [107877.42026352]
 [ 78677.87363704]
 [ 83626.95155939]
 [ 73728.7974755 ]
 [101707.57301903]
 [ 68027.46123071]
 [ 56572.00229931]
 [ 53140.64122905]
 [ 59475.45917604]
 [ 53074.65321095]
 [ 69241.63485637]
 [ 57311.06279831]
 [ 57099.9013059 ]
 [ 57891.75377444]
 [ 57363.85223625]
 [ 69241.63449325]
 [ 73992.74888866]
 [109428.12963565]
 [ 89565.84095546]
 [ 69109.65955456]
 [ 85606.57876294]
 [ 57363.85257704]
 [ 69505.58705252]
 [ 79416.93618483]
 [ 57363.85420596]
 [ 60861.1991338 ]
 [ 57363.85235594]
 [ 63170.77037133]
 [ 71881.14124495]
 [109626.09427418]
 [ 83508.17177052]
 [ 70429.41424691]
 [ 62642.86861204]
 [ 69769.53557096]
 [ 62642.86654092]
 [ 65909.25622709]
 [ 74388.67310251]
 [ 86794.35736223]
 [ 74058.73471595]
 [ 59211.50846679]
 [ 69769.53659333]
 [ 73728.79728893]
 [ 49960.0349615 ]
 [ 48290.5469466 ]
 [ 48290.5469466 ]
 [ 48290.5471677 ]
 [ 51358.97394162]
 [ 47003.78753524]
 [ 48290.5471677 ]
 [ 49148.38697276]
 [ 52982.2710246 ]
 [ 47432.70714154]
 [ 48495.10840547]
 [ 48290.54736252]
 [ 48290.54809271]
 [ 52526.95560895]
 [ 96824.48638482]
 [ 67064.04177897]
 [ 78149.97115151]
 [ 75404.88489516]
 [102499.42422177]
 [ 70429.41461003]
 [ 70099.47471424]
 [ 70429.41383098]
 [ 73728.79711238]
 [ 71749.16786004]
 [ 77688.05758687]
 [ 60531.26052614]
 [ 66338.17832043]
 [ 66338.17825355]
 [ 87256.26983762]
 [ 87586.20914919]
 [ 72936.94512665]
 [ 72936.94386085]
 [119550.63945505]
 [ 73860.77168401]
 [ 60861.1989127 ]
 [ 89565.83946856]
 [ 71089.28889611]
 [ 73629.81481342]
 [ 63830.64473254]
 [ 66602.12832577]
 [ 88576.02372466]
 [ 89565.84266346]
 [ 76632.25656537]
 [ 87586.21141908]
 [ 78479.90909587]
 [ 73385.66062846]
 [ 87916.14724777]
 [ 65810.27471112]
 [ 98804.11641621]
 [ 90357.69286211]
 [ 89381.07568009]
 [ 60795.21272229]
 [ 64794.06689242]
 [ 65645.30642052]
 [ 66800.09077349]
 [ 67196.01649657]
 [ 74124.72297748]
 [ 57786.17314995]
 [ 73728.79706783]
 [ 73728.79762972]
 [ 75312.50236802]
 [ 73728.79777174]
 [ 84814.72834319]
 [ 73728.79855473]
 [ 73728.79855473]
 [ 73728.79947974]
 [ 73728.79855473]
 [ 83461.98154251]
 [ 68119.8465674 ]
 [ 75873.39743035]
 [ 73728.79821394]
 [ 73728.79706783]
 [ 73728.79884271]
 [ 80327.56657394]
 [119260.2955249 ]
 [ 84854.31872424]
 [ 67130.02904036]
 [ 72409.04374268]
 [ 73728.79728893]
 [ 65810.27549411]
 [ 77028.18093344]
 [ 82439.17059274]
 [ 77193.15127283]
 [ 65810.27601145]
 [ 73728.79728893]
 [ 73728.79821394]
 [ 73728.79777174]
 [ 73728.7974755 ]]

In [40]:
from statsmodel.api import OLS
OLS(y,x).fit().summary()

ModuleNotFoundError: No module named 'statsmodel'

In [42]:
#converting categorical data into numercial data
df['prefarea'].head()

0    no
1    no
2    no
3    no
4    no
Name: prefarea, dtype: object

In [46]:
from sklearn.preprocessing import LabelEncoder
number=LabelEncoder()
df['prefarea']=number.fit_transform(df['prefarea'].astype('str'))

In [47]:
df['prefarea'].head()

0    0
1    0
2    0
3    0
4    0
Name: prefarea, dtype: int32