In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from math import sqrt
from sklearn.metrics import mean_squared_error

In [3]:
df=pd.read_csv('Housing.csv')
df.head()

,Unnamed: 0,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,1,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,2,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,3,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,4,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,5,61000.0,6360,2,1,1,yes,no,no,no,no,0,no

In [4]:
df.columns

Index(['Unnamed: 0', 'price', 'lotsize', 'bedrooms', 'bathrms', 'stories',
       'driveway', 'recroom', 'fullbase', 'gashw', 'airco', 'garagepl',
       'prefarea'],
      dtype='object')

In [5]:
df.tail()

,Unnamed: 0,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
541,542,91500.0,4800,3,2,4,yes,yes,no,no,yes,0,no
542,543,94000.0,6000,3,2,4,yes,no,no,no,yes,0,no
543,544,103000.0,6000,3,2,4,yes,yes,no,no,yes,1,no
544,545,105000.0,6000,3,2,2,yes,yes,no,no,yes,1,no
545,546,105000.0,6000,3,1,2,yes,no,no,no,yes,1,no

In [6]:
#what is that you want to predict
y=df['price']
print(type(y))
y=y.values
y=y.reshape(len(y),1)
print(y)

<class 'pandas.core.series.Series'>
[[ 42000.]
 [ 38500.]
 [ 49500.]
 [ 60500.]
 [ 61000.]
 [ 66000.]
 [ 66000.]
 [ 69000.]
 [ 83800.]
 [ 88500.]
 [ 90000.]
 [ 30500.]
 [ 27000.]
 [ 36000.]
 [ 37000.]
 [ 37900.]
 [ 40500.]
 [ 40750.]
 [ 45000.]
 [ 45000.]
 [ 48500.]
 [ 65900.]
 [ 37900.]
 [ 38000.]
 [ 42000.]
 [ 42300.]
 [ 43500.]
 [ 44000.]
 [ 44500.]
 [ 44900.]
 [ 45000.]
 [ 48000.]
 [ 49000.]
 [ 51500.]
 [ 61000.]
 [ 61000.]
 [ 61700.]
 [ 67000.]
 [ 82000.]
 [ 54500.]
 [ 66500.]
 [ 70000.]
 [ 82000.]
 [ 92000.]
 [ 38000.]
 [ 44000.]
 [ 41000.]
 [ 43000.]
 [ 48000.]
 [ 54800.]
 [ 55000.]
 [ 57000.]
 [ 68000.]
 [ 95000.]
 [ 38000.]
 [ 25000.]
 [ 25245.]
 [ 56000.]
 [ 35500.]
 [ 30000.]
 [ 48000.]
 [ 48000.]
 [ 52000.]
 [ 54000.]
 [ 56000.]
 [ 60000.]
 [ 60000.]
 [ 67000.]
 [ 47000.]
 [ 70000.]
 [ 45000.]
 [ 51000.]
 [ 32500.]
 [ 34000.]
 [ 35000.]
 [ 36000.]
 [ 45000.]
 [ 47000.]
 [ 55000.]
 [ 63900.]
 [ 50000.]
 [ 35000.]
 [ 50000.]
 [ 43000.]
 [ 55500.]
 [ 57000.]
 [ 60000.]
 [ 78000.]
 [ 35000.]
 [ 44000.]
 [ 47000.]
 [ 58000.]
 [163000.]
 [128000.]
 [123500.]
 [ 39000.]
 [ 53900.]
 [ 59900.]
 [ 35000.]
 [ 43000.]
 [ 57000.]
 [ 79000.]
 [125000.]
 [132000.]
 [ 58000.]
 [ 43000.]
 [ 48000.]
 [ 58500.]
 [ 73000.]
 [ 63500.]
 [ 43000.]
 [ 46500.]
 [ 92000.]
 [ 75000.]
 [ 75000.]
 [ 85000.]
 [ 93000.]
 [ 94500.]
 [106500.]
 [116000.]
 [ 61500.]
 [ 80000.]
 [ 37000.]
 [ 59500.]
 [ 70000.]
 [ 95000.]
 [117000.]
 [122500.]
 [123500.]
 [127000.]
 [ 35000.]
 [ 44500.]
 [ 49900.]
 [ 50500.]
 [ 65000.]
 [ 90000.]
 [ 46000.]
 [ 35000.]
 [ 26500.]
 [ 43000.]
 [ 56000.]
 [ 40000.]
 [ 51000.]
 [ 51000.]
 [ 57250.]
 [ 44000.]
 [ 61000.]
 [ 62000.]
 [ 80000.]
 [ 50000.]
 [ 59900.]
 [ 35500.]
 [ 37000.]
 [ 42000.]
 [ 48000.]
 [ 60000.]
 [ 60000.]
 [ 60000.]
 [ 62000.]
 [ 63000.]
 [ 63900.]
 [130000.]
 [ 25000.]
 [ 50000.]
 [ 52900.]
 [ 62000.]
 [ 73500.]
 [ 38000.]
 [ 46000.]
 [ 48000.]
 [ 52500.]
 [ 32000.]
 [ 38000.]
 [ 46000.]
 [ 50000.]
 [ 57500.]
 [ 70000.]
 [ 69900.]
 [ 74500.]
 [ 42000.]
 [ 60000.]
 [ 50000.]
 [ 58000.]
 [ 63900.]
 [ 28000.]
 [ 54000.]
 [ 44700.]
 [ 47000.]
 [ 50000.]
 [ 57250.]
 [ 67000.]
 [ 52500.]
 [ 42000.]
 [ 57500.]
 [ 33000.]
 [ 34400.]
 [ 40000.]
 [ 40500.]
 [ 46500.]
 [ 52000.]
 [ 53000.]
 [ 53900.]
 [ 50000.]
 [ 55500.]
 [ 56000.]
 [ 60000.]
 [ 60000.]
 [ 69500.]
 [ 72000.]
 [ 92500.]
 [ 40500.]
 [ 42000.]
 [ 47900.]
 [ 52000.]
 [ 62000.]
 [ 41000.]
 [138300.]
 [ 42000.]
 [ 47000.]
 [ 64500.]
 [ 46000.]
 [ 58000.]
 [ 70100.]
 [ 78500.]
 [ 87250.]
 [ 70800.]
 [ 56000.]
 [ 48000.]
 [ 68000.]
 [ 79000.]
 [ 80000.]
 [ 87000.]
 [ 25000.]
 [ 32500.]
 [ 36000.]
 [ 42500.]
 [ 43000.]
 [ 50000.]
 [ 26000.]
 [ 30000.]
 [ 34000.]
 [ 52000.]
 [ 70000.]
 [ 27000.]
 [ 32500.]
 [ 37200.]
 [ 38000.]
 [ 42000.]
 [ 44500.]
 [ 45000.]
 [ 48500.]
 [ 52000.]
 [ 53900.]
 [ 60000.]
 [ 61000.]
 [ 64500.]
 [ 71000.]
 [ 75500.]
 [ 33500.]
 [ 41000.]
 [ 41000.]
 [ 46200.]
 [ 48500.]
 [ 48900.]
 [ 50000.]
 [ 51000.]
 [ 52500.]
 [ 52500.]
 [ 54000.]
 [ 59000.]
 [ 60000.]
 [ 63000.]
 [ 64000.]
 [ 64900.]
 [ 65000.]
 [ 66000.]
 [ 70000.]
 [ 65500.]
 [ 57000.]
 [ 52000.]
 [ 54000.]
 [ 74500.]
 [ 90000.]
 [ 45000.]
 [ 45000.]
 [ 65000.]
 [ 55000.]
 [ 62000.]
 [ 30000.]
 [ 34000.]
 [ 38000.]
 [ 39000.]
 [ 45000.]
 [ 47000.]
 [ 47500.]
 [ 49000.]
 [ 50000.]
 [ 50000.]
 [ 52900.]
 [ 53000.]
 [ 55000.]
 [ 56000.]
 [ 58500.]
 [ 59500.]
 [ 60000.]
 [ 64000.]
 [ 67000.]
 [ 68100.]
 [ 70000.]
 [ 72000.]
 [ 57500.]
 [ 69900.]
 [ 70000.]
 [ 75000.]
 [ 76900.]
 [ 78000.]
 [ 80000.]
 [ 82000.]
 [ 83000.]
 [ 83000.]
 [ 83900.]
 [ 88500.]
 [ 93000.]
 [ 98000.]
 [ 98500.]
 [ 99000.]
 [101000.]
 [110000.]
 [115442.]
 [120000.]
 [124000.]
 [175000.]
 [ 50000.]
 [ 55000.]
 [ 60000.]
 [ 61000.]
 [106000.]
 [155000.]
 [141000.]
 [ 62500.]
 [ 70000.]
 [ 73000.]
 [ 80000.]
 [ 80000.]
 [ 88000.]
 [ 49000.]
 [ 52000.]
 [ 59500.]
 [ 60000.]
 [ 64000.]
 [ 64500.]
 [ 68500.]
 [ 78500.]
 [ 86000.]
 [ 86900.]
 [ 75000.]
 [ 78000.]
 [ 95000.]
 [ 97000.]
 [107000.]
 [130000.]
 [145000.]
 [175000.]
 [ 72000.]
 [ 84900.]
 [ 99000.]
 [114000.]
 [120000.]
 [145000.]
 [ 79000.]
 [ 82000.]
 [ 85000.]
 [100500.]
 [122000.]
 [126500.]
 [133000.]
 [140000.]
 [190000.]
 [ 84000.]
 [ 97000.]
 [103500.]
 [112500.]
 [140000.]
 [ 74700.]
 [ 78000.]
 [ 78900.]
 [ 83900.]
 [ 85000.]
 [ 85000.]
 [ 86000.]
 [ 86900.]
 [ 94500.]
 [ 96000.]
 [106000.]
 [ 72000.]
 [ 74500.]
 [ 77000.]
 [ 80750.]
 [ 82900.]
 [ 85000.]
 [ 92500.]
 [ 76000.]
 [ 77500.]
 [ 80000.]
 [ 80000.]
 [ 86000.]
 [ 87000.]
 [ 87500.]
 [ 89000.]
 [ 89900.]
 [ 90000.]
 [ 95000.]
 [112000.]
 [ 31900.]
 [ 52000.]
 [ 90000.]
 [100000.]
 [ 91700.]
 [174500.]
 [ 94700.]
 [ 68000.]
 [ 80000.]
 [ 61100.]
 [ 62900.]
 [ 65500.]
 [ 66000.]
 [ 49500.]
 [ 50000.]
 [ 53500.]
 [ 58550.]
 [ 64500.]
 [ 65000.]
 [ 69000.]
 [ 73000.]
 [ 75000.]
 [ 75000.]
 [132000.]
 [ 60000.]
 [ 65000.]
 [ 69000.]
 [ 51900.]
 [ 57000.]
 [ 65000.]
 [ 79500.]
 [ 72500.]
 [104900.]
 [114900.]
 [120000.]
 [ 58000.]
 [ 67000.]
 [ 67000.]
 [ 69000.]
 [ 73000.]
 [ 73500.]
 [ 74900.]
 [ 75000.]
 [ 79500.]
 [120900.]
 [ 44555.]
 [ 47000.]
 [ 47600.]
 [ 49000.]
 [ 49000.]
 [ 49000.]
 [ 49500.]
 [ 52000.]
 [ 54000.]
 [ 55000.]
 [ 55000.]
 [ 56000.]
 [ 60000.]
 [ 60500.]
 [ 50000.]
 [ 64900.]
 [ 93000.]
 [ 85000.]
 [ 61500.]
 [ 88500.]
 [ 88000.]
 [ 89000.]
 [ 89500.]
 [ 95000.]
 [ 95500.]
 [ 51500.]
 [ 62900.]
 [118500.]
 [ 42900.]
 [ 44100.]
 [ 47000.]
 [ 50000.]
 [ 50000.]
 [ 53000.]
 [ 53000.]
 [ 54000.]
 [ 58500.]
 [ 59000.]
 [ 60000.]
 [ 62900.]
 [ 64000.]
 [ 65000.]
 [ 67900.]
 [ 68500.]
 [ 70000.]
 [ 70500.]
 [ 71500.]
 [ 71900.]
 [ 75000.]
 [ 75000.]
 [ 87000.]
 [ 64000.]
 [ 70000.]
 [ 47500.]
 [ 62600.]
 [ 66000.]
 [ 58900.]
 [ 53000.]
 [ 95000.]
 [ 96500.]
 [101000.]
 [102000.]
 [103000.]
 [105000.]
 [108000.]
 [110000.]
 [113000.]
 [120000.]
 [105000.]
 [106000.]
 [107500.]
 [108000.]
 [113750.]
 [120000.]
 [ 70000.]
 [ 71000.]
 [ 82000.]
 [ 82000.]
 [ 82500.]
 [ 83000.]
 [ 84000.]
 [ 85000.]
 [ 85000.]
 [ 91500.]
 [ 94000.]
 [103000.]
 [105000.]
 [105000.]]

In [7]:
degree=[1,2,3]
x=df['lotsize']
lt=pd.cut(x,3,labels=degree)
print(lt)

0      1
1      1
2      1
3      2
4      1
5      1
6      1
7      1
8      1
9      1
10     2
11     1
12     1
13     1
14     1
15     1
16     1
17     1
18     1
19     1
20     1
21     1
22     1
23     1
24     1
25     1
26     1
27     1
28     1
29     1
      ..
516    1
517    1
518    1
519    1
520    2
521    1
522    1
523    1
524    1
525    2
526    1
527    1
528    1
529    1
530    1
531    2
532    3
533    2
534    1
535    1
536    1
537    1
538    1
539    2
540    2
541    1
542    1
543    1
544    1
545    1
Name: lotsize, Length: 546, dtype: category
Categories (3, int64): [1 < 2 < 3]

In [9]:
df['lt']=lt
df['lt']=df['lt'].astype('category')
x=df[['lt','bedrooms']]
#x=x.values
#x=x.reshape(len(x),1)
print(x)

    lt  bedrooms
0    1         3
1    1         2
2    1         3
3    2         3
4    1         2
5    1         3
6    1         3
7    1         3
8    1         3
9    1         3
10   2         3
11   1         2
12   1         3
13   1         3
14   1         2
15   1         2
16   1         3
17   1         4
18   1         1
19   1         2
20   1         3
21   1         4
22   1         3
23   1         2
24   1         2
25   1         2
26   1         2
27   1         2
28   1         3
29   1         3
..  ..       ...
516  1         3
517  1         4
518  1         4
519  1         3
520  2         4
521  1         4
522  1         4
523  1         4
524  1         4
525  2         3
526  1         3
527  1         3
528  1         3
529  1         3
530  1         3
531  2         3
532  3         3
533  2         3
534  1         3
535  1         3
536  1         3
537  1         3
538  1         3
539  2         4
540  2         3
541  1         3
542  1         3
543  1         3
544  1         3
545  1         3

[546 rows x 2 columns]

In [10]:
x_train=x[:430]
x_test=x[431:]
y_train=y[:430]
y_test=y[431:]
regr=linear_model.LinearRegression()
regr.fit(x_train,y_train)
pred=regr.predict(x_test)
print(pred)

[[ 60179.96035135]
 [ 60179.96035135]
 [105452.90448845]
 [ 88004.53661861]
 [ 70556.16874877]
 [ 88004.53661861]
 [ 60179.96035135]
 [ 60179.96035135]
 [ 88004.53661861]
 [ 60179.96035135]
 [ 49803.75195393]
 [ 60179.96035135]
 [ 70556.16874877]
 [ 49803.75195393]
 [126205.32128328]
 [ 88004.53661861]
 [ 70556.16874877]
 [ 60179.96035135]
 [ 49803.75195393]
 [ 60179.96035135]
 [ 49803.75195393]
 [ 60179.96035135]
 [ 88004.53661861]
 [ 60179.96035135]
 [ 60179.96035135]
 [ 80932.37714618]
 [ 60179.96035135]
 [ 60179.96035135]
 [ 60179.96035135]
 [ 60179.96035135]
 [ 60179.96035135]
 [ 60179.96035135]
 [ 60179.96035135]
 [ 60179.96035135]
 [ 60179.96035135]
 [ 60179.96035135]
 [ 60179.96035135]
 [ 49803.75195393]
 [ 70556.16874877]
 [ 60179.96035135]
 [ 60179.96035135]
 [ 88004.53661861]
 [ 70556.16874877]
 [ 88004.53661861]
 [ 70556.16874877]
 [ 77628.32822119]
 [ 60179.96035135]
 [ 70556.16874877]
 [ 60179.96035135]
 [ 70556.16874877]
 [ 60179.96035135]
 [ 77628.32822119]
 [ 49803.75195393]
 [ 60179.96035135]
 [ 70556.16874877]
 [ 77628.32822119]
 [ 77628.32822119]
 [ 60179.96035135]
 [ 49803.75195393]
 [115829.11288586]
 [ 60179.96035135]
 [ 49803.75195393]
 [ 77628.32822119]
 [ 49803.75195393]
 [ 60179.96035135]
 [ 60179.96035135]
 [ 60179.96035135]
 [ 88004.53661861]
 [ 98380.74501602]
 [ 49803.75195393]
 [ 98380.74501602]
 [ 88004.53661861]
 [ 60179.96035135]
 [ 88004.53661861]
 [ 49803.75195393]
 [ 98380.74501602]
 [ 88004.53661861]
 [ 88004.53661861]
 [ 60179.96035135]
 [ 60179.96035135]
 [ 70556.16874877]
 [ 70556.16874877]
 [ 60179.96035135]
 [ 49803.75195393]
 [ 49803.75195393]
 [ 60179.96035135]
 [ 70556.16874877]
 [ 70556.16874877]
 [ 60179.96035135]
 [ 98380.74501602]
 [ 70556.16874877]
 [ 70556.16874877]
 [ 70556.16874877]
 [ 70556.16874877]
 [ 88004.53661861]
 [ 60179.96035135]
 [ 60179.96035135]
 [ 60179.96035135]
 [ 60179.96035135]
 [ 60179.96035135]
 [ 88004.53661861]
 [115829.11288586]
 [ 88004.53661861]
 [ 60179.96035135]
 [ 60179.96035135]
 [ 60179.96035135]
 [ 60179.96035135]
 [ 60179.96035135]
 [ 98380.74501602]
 [ 88004.53661861]
 [ 60179.96035135]
 [ 60179.96035135]
 [ 60179.96035135]
 [ 60179.96035135]
 [ 60179.96035135]]

In [11]:
rms=sqrt(mean_squared_error(y_test,pred))
print(rms)

25220.30071140893

In [25]:
from sklearn.preprocessing import LabelEncoder
number=LabelEncoder()
df['prefarea']=number.fit_transform(df['prefarea'].astype('str'))
df['']=number
print(df['prefarea'])

0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     0
11     0
12     0
13     0
14     0
15     0
16     0
17     0
18     0
19     0
20     0
21     0
22     0
23     0
24     0
25     0
26     0
27     0
28     0
29     0
      ..
516    0
517    0
518    0
519    0
520    0
521    0
522    0
523    0
524    0
525    0
526    0
527    0
528    0
529    0
530    0
531    0
532    0
533    0
534    0
535    0
536    0
537    0
538    0
539    0
540    0
541    0
542    0
543    0
544    0
545    0
Name: prefarea, Length: 546, dtype: int32